[project]
name = "HomeOffer--backend"
version = "0.1.0"
description = "API for HomeOffer"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.120.2",
    "uvicorn>=0.38.0",
]
